#include:
#    - template: Code-Quality.gitlab-ci.yml

#code_quality:
#    artifacts:
#        paths: [gl-code-quality-report.json]

#GENERAL SETTINGS

# Top-level general rules determine when this pipeline is run:
# - only on merge requests, new tags and changes to dev
# - NOT on any branch except dev
# - will run detached merge request pipelines for any merge request,
#   targeting any branch
# Read more on when to use this template at
# https://docs.gitlab.com/ee/ci/yaml/#workflowrules
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_IID
        - if: $CI_COMMIT_TAG
        - if: $CI_COMMIT_BRANCH == "dev"

stages:
    - static_checks
    - build_depends
    - build
    - benchmark_tests

cache: &global_cache_settings
    paths:
        - ccache/

.ubuntu_base:
    image: bchunlimited/nexa:ubuntu20.04

.ubuntu_ccache_scripts:
    extends: .ubuntu_base
    before_script:
        - mkdir -p ccache
        - export CCACHE_BASEDIR=${PWD}
        - export CCACHE_DIR=${PWD}/ccache
        - export CCACHE_COMPILERCHECK=content
        - ccache --zero-stats || true

# Linting
.ubuntu_cache-linting:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: linting_cache

check-formatting:
    stage: static_checks
    extends: .ubuntu_cache-linting
    needs: []
    script:
        - ./autogen.sh
        - ./configure --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports
        - make check-formatting

# x86_64 Linux + deps as via system lib
.cache-ubuntu-nodeps:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: ubuntu_cache-nodeps

build-ubuntu-nodeps:
    stage: build
    extends: .cache-ubuntu-nodeps
    needs: []
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --cache-file=config.cache --with-incompatible-bdb --with-gui=no --enable-glibc-back-compat --enable-reduce-exports
        - make -j `nproc`
        - ccache --show-stats
        - make check
    artifacts:
        when: always
        paths:
            - ./build/src/nexad
            - ./build/src/nexa-cli
            - ./build/src/nexa-miner
            - ./build/src/nexa-tx
            - ./build/src/test/test_nexa
            - ./build/src/bench/bench_nexa
            - ./build/src/test/*.log
            - ./src/test/*.log
            - ./src/test-suite.log

build-ubuntu-nodeps-qt:
    stage: build
    extends: .cache-ubuntu-nodeps
    needs: []
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --cache-file=config.cache --with-incompatible-bdb --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --disable-bench --disable-tests
        - make -j `nproc`
        - ccache --show-stats
    artifacts:
        paths:
            - ./build/src/nexad
            - ./build/src/nexa-cli
            - ./build/src/nexa-miner
            - ./build/src/nexa-tx

# Linux 64 bit, source deps
.cache-ubuntu:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: ubuntu_cache
        paths:
            - ccache/
            - depends/sources
            - depends/built
            - depends/x86_64-unknown-linux-gnu

build-ubuntu-deps:
    stage: build_depends
    extends: .cache-ubuntu
    needs: []
    script:
        - cd depends
        - make HOST=x86_64-unknown-linux-gnu -j `nproc`
    artifacts:
        paths:
            - depends/x86_64-unknown-linux-gnu

build-ubuntu:
    stage: build
    extends: .cache-ubuntu
    needs: [build-ubuntu-deps]
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --enable-shared --enable-debug --enable-zmq --enable-glibc-back-compat --enable-reduce-exports --cache-file=config.cache --prefix=$PWD/../depends/x86_64-unknown-linux-gnu CPPFLAGS=-DDEBUG_LOCKORDER
        - make -j `nproc`
        - make -j `nproc` check
        - ccache --show-stats
        - mkdir -p $CI_PROJECT_DIR/cores
        - mkdir -p $CI_PROJECT_DIR/saved-cores
        - echo $CI_PROJECT_DIR/cores/core.%e.%p.%h.%t | tee /proc/sys/kernel/core_pattern
        - ./qa/pull-tester/rpc-tests.py --coverage --no-ipv6-rpc-listen --gitlab
    dependencies:
        - build-ubuntu-deps
    artifacts:
        when: on_failure
        paths:
            - ./build/src/nexad
            - ./build/src/nexa-cli
            - ./build/src/nexa-miner
            - ./build/src/nexa-tx
            - ./build/src/test/
            - ./build/src/test/test_nexa
            - ./build/src/bench/bench_nexa
            - ./build/src/test/*.log
            - ./src/test/*.log
            - ./src/test-suite.log

build-debian-rostrum:
    extends: .ubuntu_base
    stage: build
    cache:
      paths:
        # Paths from Cargo Book, section "Caching the Cargo home in CI"
        - cargohome/bin
        - cargohome/registry/index
        - cargohome/registry/cache
        - cargohome/git/db

    needs: [build-ubuntu-deps]

    variables:
      CARGO_HOME: ${CI_PROJECT_DIR}/cargohome

    before_script:
      - mkdir -p cargohome
      - mkdir -p build

    script:
        # add cargo to PATH
        - export PATH=$PATH:`pwd`/depends/x86_64-unknown-linux-gnu/native/bin

        # Prepare make file
        - ./autogen.sh > /dev/null
        - cd build
        - ../configure --cache-file=config.cache
            --prefix=$PWD/../depends/x86_64-unknown-linux-gnu > /dev/null

        - make rostrum

    dependencies:
        - build-ubuntu-deps

    artifacts:
        paths:
            - ./build/src/rostrum

test-ubuntu-benchmarks:
    extends: .ubuntu_base
    stage: benchmark_tests
    #extends: .cache-ubuntu
    needs: ["build-ubuntu-nodeps"]
    script:
        - (./build/src/bench/bench_nexa -evals=1)
    dependencies:
        - build-ubuntu-nodeps

# nexad clang (no depend, only system lib installed via apt)
.cache-ubuntu-clang:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: ubuntu_cache_clang

.ubuntu-clang-env:
    extends: .cache-ubuntu-clang
    variables:
        CC: clang-12
        CXX: clang++-12

build-ubuntu-clang:
    stage: build
    extends: .ubuntu-clang-env
    needs: []
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --cache-file=config.cache --enable-zmq --with-gui=qt5 --with-incompatible-bdb CPPFLAGS=-DDEBUG_LOCKORDER
        - make -j `nproc`
        - ccache --show-stats
        - make check
    artifacts:
        paths:
            - ./build/src/nexad
            - ./build/src/nexa-cli
            - ./build/src/nexa-miner
            - ./build/src/nexa-tx
            - ./build/src/test/
            - ./build/src/test/test_nexa
            - ./build/src/test/*.log
            - ./src/test/*.log
            - ./src/test-suite.log

# ARM64
.cache-arm-64:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: arm_cache-64
        paths:
            - ccache/
            - depends/sources
            - depends/built
            - depends/aarch64-linux-gnu

build-arm-depends-64:
    stage: build_depends
    extends: .cache-arm-64
    script:
        - cd depends
        - make HOST=aarch64-linux-gnu NO_QT=1 -j `nproc` NO_RUST=1
    artifacts:
        paths:
            - depends/aarch64-linux-gnu

build-arm-64:
    stage: build
    extends: .cache-arm-64
    needs: ["build-arm-depends-64"]
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --prefix=$PWD/../depends/aarch64-linux-gnu --enable-glibc-back-compat --enable-reduce-exports CXXFLAGS=-Wno-psabi
        - make -j `nproc`
        - ccache --show-stats
    dependencies:
        - build-arm-depends-64

# ARM32
.cache-arm-32:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: arm_cache-32
        paths:
            - ccache/
            - depends/sources
            - depends/built
            - depends/arm-linux-gnueabihf

build-arm-depends-32:
    stage: build_depends
    extends: .cache-arm-32
    script:
        - cd depends
        - make HOST=arm-linux-gnueabihf NO_QT=1 -j `nproc` NO_RUST=1
    artifacts:
        paths:
            - depends/arm-linux-gnueabihf

build-arm-32:
    stage: build
    extends: .cache-arm-32
    needs: ["build-arm-depends-32"]
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --prefix=$PWD/../depends/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports
        - make -j `nproc`
        - ccache --show-stats
    dependencies:
        - build-arm-depends-32

# Win64
.cache-win-64:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: win_cache-64
        paths:
            - ccache/
            - depends/sources
            - depends/built
            - depends/x86_64-w64-mingw32

build-win-64-depends:
    stage: build_depends
    extends: .cache-win-64
    script:
        - cd depends
        - make HOST=x86_64-w64-mingw32 NO_QT=1 -j `nproc` NO_RUST=1
    artifacts:
        paths:
            - depends/x86_64-w64-mingw32

build-win-64:
    stage: build
    extends: .cache-win-64
    needs: ["build-win-64-depends"]
    script:
        - ./autogen.sh
        - - mkdir build; cd build
        - ../configure --enable-reduce-exports --prefix=$PWD/../depends/x86_64-w64-mingw32
        - make -j `nproc`
        - ccache --show-stats
    dependencies:
        - build-win-64-depends

# OSX
.cache-osx:
    extends: .ubuntu_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: osx_cache
        paths:
            - ccache/
            - depends/sources
            - depends/built
            - depends/x86_64-apple-darwin19

build-osx-depends:
    stage: build_depends
    extends: .cache-osx
    script:
        - mkdir -p depends/sdk-sources; mkdir depends/SDKs
        - curl --location --fail https://www.bitcoinunlimited.info/sdks/MacOSX10.15.sdk.tar.xz -o ./depends/sdk-sources/MacOSX10.15.sdk.tar.xz
        - tar -C depends/SDKs -xf depends/sdk-sources/MacOSX10.15.sdk.tar.xz
        - cd depends
        - make HOST=x86_64-apple-darwin19 -j `nproc` NO_RUST=1
        - ccache --show-stats
    artifacts:
        paths:
            - depends/x86_64-apple-darwin19
            - depends/SDKs

build-osx:
    stage: build
    extends: .cache-osx
    needs: ["build-osx-depends"]
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --enable-reduce-exports --prefix=$PWD/../depends/x86_64-apple-darwin19
        - make -j `nproc`
        - ccache --show-stats
    dependencies:
        - build-osx-depends
    artifacts:
        when: on_failure
        paths:
            - build/config.log
            - depends/x86_64-apple-darwin19/share/config.site


###### Debian CI tests

.debian_base:
    image: bchunlimited/gitlabci:debian11

.debian_ccache_scripts:
    extends: .debian_base
    before_script:
        - mkdir -p ccache
        - export CCACHE_BASEDIR=${PWD}
        - export CCACHE_DIR=${PWD}/ccache
        - export CCACHE_COMPILERCHECK=content
        - ccache --zero-stats || true

 # x86_64 Debian + deps as via system lib
.cache-debian-nodeps:
    extends: .debian_ccache_scripts
    cache:
        <<: *global_cache_settings
        key: debian_cache-nodeps

build-debian-nodeps:
    stage: build
    extends: .cache-debian-nodeps
    needs: []
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --cache-file=config.cache --with-incompatible-bdb --with-gui=no --enable-glibc-back-compat --enable-reduce-exports
        - make -j `nproc`
        - ccache --show-stats
        - make check
    artifacts:
        when: always
        paths:
            - ./build/src/nexad
            - ./build/src/nexa-cli
            - ./build/src/nexa-miner
            - ./build/src/nexa-tx
            - ./build/src/test/test_nexa
            - ./build/src/bench/bench_nexa
            - ./build/src/test/*.log
            - ./src/test/*.log
            - ./src/test-suite.log

build-debian-nodeps-qt:
    stage: build
    extends: .cache-debian-nodeps
    needs: []
    script:
        - ./autogen.sh
        - mkdir build; cd build
        - ../configure --cache-file=config.cache --with-incompatible-bdb --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --disable-bench --disable-tests
        - make -j `nproc`
        - ccache --show-stats
    artifacts:
        paths:
            - ./build/src/nexad
            - ./build/src/nexa-cli
            - ./build/src/nexa-miner
            - ./build/src/nexa-tx
